# Generated by Django 4.1.12 on 2023-11-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="balance",
            field=models.IntegerField(default=0, verbose_name="Баланс"),
        ),
    ]
